### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by kuntaek6** [muyeby/AMR-Backparsing#1]
Hello.
I have some questions for preprocessing.
 
I tried to make data which has equal format of your sample data for using your models.
Using subword-nmt, I made some data whose format is equal to 'dev.amr', 'dev.amr.bpe', 'dev.concept.bpe', 'dev.sent', 'dev.tok.sent.bpe'.
However, i don't know how to get 'dev.path', 'dev.rel', 'dev.rel.lst', 'dev.rel.mat', 'dev.align.matrix' format from formal AMR graph.
and also each files' meaning.

Could you explain details of those files or uploading preprocessing code?

**Comment by goodbai-nlp** [comment]
Hi, 

Thanks for your attention to our work. Assuming that an input AMR graph has N nodes after bpe (we add a dummy root node to the graph) and the corresponding text has M tokens after bpe, then

Each line of 'dev.path'  includes N*N terms, storing the "relation" matrix of the AMR graph. For example, the "relation" between node_{i} and node_{j} are stored at the _ixj_ th term. The "relation" here refers to the shortest path in AMR graph between node_{i} and node_{j}.
   
   Each line of 'dev.rel'  includes M*M terms, storing the relation mask matrix of the target side sentence. For example, the relation mask between word_{i} and word_{j} are stored at the _i x j_ th term.

   Each line of 'dev.rel.lst' stores the relation **list** of the target side sentence. For example, when relation mask value is 1, 'dev.rel.lst' stores a relation.

   Each line of 'dev.rel.mat' stores the relation **matrix** of the target side sentence. For example, 'dev.rel.lst' stores a relation when relation mask value is 1,  'dev.rel.lst' stores <blank> relation otherwise.
   
   Each line of 'dev.align.matrix' includes M*N terms, stores the alignment **matrix** of the target side sentence. For example, if the _m_ th word is aligned with _n_ th node, the _mxn_ th value in 'dev.align.matrix' will be 1. It should be noted that meaningless words will be aligned with the dummy node.

**Comment by kuntaek6** [comment]
Thank you for your detailed explanation.
It was very helpful for understanding.

However, I'm still confused about ':sub' and ':EOS' in these files.

In 'dev.path', I think ':sub' is a relationship from BPE, whose role is connecting splited tokens to the head token of a original word.
For example, 'sulaiman' is splited 4 tokens ('su@@', 'la@@', 'i@@', 'man'). And 3 tokens('la@@', 'i@@', 'man') are connected to 'su@@' with ':sub' relationship like <su@@, :sub, la@@>, <su@@, :sub, i@@>, <su@@, :sub, man>. Does it right?

And, ':EOS' looks like a relationship between a dummy root node and the top of nodes. But I cannot understand its direction (+/-). [Here](https://github.com/kuntaek6/About_Questions/blob/main/dev.0.path.csv) is a file of  the 'dev.path's first line which I add a concept column and row with split for convenience. I don't know why the direction from 'and' to 'lawyer' has a same direction from 'and' to 'ROOT'.

In 'dev.rel.mat', I cannot speak what ':EOS' means.
I could figure out relations from the [matrix](https://github.com/kuntaek6/About_Questions/blob/main/dev.0.rel.mat.csv) such as <had, +:op2, and>, <had, -:time, former>, <had, -:ARG3, judge> and etc..
but I donn't know why there are lots of ':EOS' relations. <al, +:EOS, su@@>, <@-@, +:EOS, su@@>, <is, +:EOS, su@@>, ... .

I think I may misunderstand something. Could you explain about above things?

**Comment by goodbai-nlp** [comment]
Hi, 

You are right that ':sub' is a relationship from BPE. It starts from the first token to other tokens.

It also true that ':EOS'  is a relationship between a dummy root node and the top of nodes. This relation starts from **the top node** to the **root node**.  Its direction looks a little weird :). However, I do not change that in order to compare with our baseline model (see [here](https://github.com/Amazing-J/structural-transformer)). 

About the edge direction, '+' stands for out edge and '-' stands for in edge.

In 'dev.rel.mat', when one target token does not have any out edges to other tokens, we add one ':EOS' relation from this token to the first token. This ensures that each token has one edge at least, which is helpful for training.

**Comment by kuntaek6** [comment]
Thanks for your help. 
I close this issues.
